### PR TITLE
Catch exception on login failure; this was causing node-red to crash …

### PR DESCRIPTION
**Pull request by joshua-nord**
…when Tesla login failed in certain ways. Was reproducible with only an auth node, a valid username, and an empty password field.

Log showing crash prior to fix:
```
[teslams] Telsa login error: [object Object]
28 Jan 09:09:46 - [red] Uncaught Exception:
28 Jan 09:09:46 - TypeError: Cannot read property 'response' of undefined
    at /Users/jnord/dev/scratch/node-red-contrib-teslams/teslams/teslams.js:34:43
    at report (/Users/jnord/dev/scratch/node-red-contrib-teslams/node_modules/teslams/teslams.js:25:13)
    at Request._callback (/Users/jnord/dev/scratch/node-red-contrib-teslams/node_modules/teslams/teslams.js:66:101)
    at Request.self.callback (/Users/jnord/dev/scratch/node-red-contrib-teslams/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/jnord/dev/scratch/node-red-contrib-teslams/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/jnord/dev/scratch/node-red-contrib-teslams/node_modules/request/request.js:1085:12)

```

### CODE REVIEW

**Comment by cbrandlehner** [comment]
I had the problem that Node-Red was crashing every time after triggering the login node.
Applying this fix prevented the crash and instead shows a login error on the console.

I am sure I used correct username and password, anybody else having login problems? Probably Tesla changed the API?

**Comment by joshua-nord** [comment]
Yes; the last few days I've been having issues with my node-red tesla plugin, and my streaming server that uses the same teslams module.

I see the response coming back from Tesla's servers as: `Our servers are waiting for a supercharger spot..`

It looks like we are not alone, trying to apply the advice from this thread now: https://teslamotorsclub.com/tmc/threads/error-in-tesla-api.127239/

**Comment by cbrandlehner** [comment]
I created a pull request on teslams:
https://github.com/hjespers/teslams/pull/126

However, the fix on teslams should go along with the fix in this pull request #2

**Comment by flexgames** [comment]
Can you confirm that streaming works with these changes? Still no luck on my side.

**Comment by hjespers** [comment]
Merged the PR on Github but not yet published to npm.

**Pull request merged**
